{
    'name': 'Stock Return to Original Location',
    'version': '18.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Return products to the same source location of the original delivery',
    'author': 'Mohamed Saied',
    'website': 'https://wa.me/201013907174',
    'depends': ['stock'],
    'data': [],
    'installable': True,
    'license': 'LGPL-3',
    'price': 25.0,
    'currency': 'USD',
    'images': ['static/description/banner.gif'],
}
