{
    'name': 'Return to Original Source Location',
    'version': '19.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Stock returns automatically go back to the source location of the original delivery order.',
    'author': 'Mohamed Saied',
    'support': 'MohamedSaiedd53@gmail.com',
    'depends': ['stock'],
    'data': [],
    'installable': True,
    'license': 'LGPL-3',
    'price': 25.0,
    'currency': 'USD',
    'images': ['static/description/banner.gif'],
}
