{
    'name': 'Ledger Currency Totals - Partner & General Ledger',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Add amount-currency totals to the Partner Ledger & General Ledger reports. Multi-currency ledger totals.',
    'depends': ['account_reports'],
    'data': ['views/account_move_line_views.xml',],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    'price': 15.0,
    'currency': 'USD',
    'author': 'Mohamed Saied',
    'images': ['static/description/banner.gif'],
}
