{
    'name': 'Ledger Currency Totals - Partner & General Ledger',
    'version': '17.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Add amount-currency totals to the Partner Ledger & General Ledger reports. Multi-currency ledger totals.',
    'depends': ['account_reports'],
    'data': ['views/account_move_line_views.xml',],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    "price": 15,
    "currency": "USD",
    'author': 'Mohamed Saied',
    'support': 'MohamedSaiedd53@gmail.com',
    'images': ['static/description/banner.gif'],
}